// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBytjC6sryTziMOqW8Qf0KoQVKHXIezLuY',
    appId: '1:179585942268:android:7a3b07216e28963a5e0d79',
    messagingSenderId: '179585942268',
    projectId: 'emodiary-6cf14',
    storageBucket: 'emodiary-6cf14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxgQUzgdYmrkzokitNjTFu0FynD3LKQ04',
    appId: '1:179585942268:ios:8fd5adf28c6daece5e0d79',
    messagingSenderId: '179585942268',
    projectId: 'emodiary-6cf14',
    storageBucket: 'emodiary-6cf14.appspot.com',
    iosClientId: '179585942268-9ochf1m7m60o6bhr6di16rbmolpu239d.apps.googleusercontent.com',
    iosBundleId: 'com.example.emodiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxgQUzgdYmrkzokitNjTFu0FynD3LKQ04',
    appId: '1:179585942268:ios:8fd5adf28c6daece5e0d79',
    messagingSenderId: '179585942268',
    projectId: 'emodiary-6cf14',
    storageBucket: 'emodiary-6cf14.appspot.com',
    iosClientId: '179585942268-9ochf1m7m60o6bhr6di16rbmolpu239d.apps.googleusercontent.com',
    iosBundleId: 'com.example.emodiary',
  );

}